2025-10-06 13:26:10,368 ERROR: Exception on / [GET] [in /Users/jeremybullis/Desktop/F1DataProject/venv/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/jeremybullis/Desktop/F1DataProject/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremybullis/Desktop/F1DataProject/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremybullis/Desktop/F1DataProject/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremybullis/Desktop/F1DataProject/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremybullis/Desktop/F1DataProject/app/routes.py", line 73, in index
    return render_template('index.html', drivers=session_result, session_name=session_name, year=year, circuit_name=circuit_name, circuit=circuit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremybullis/Desktop/F1DataProject/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremybullis/Desktop/F1DataProject/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremybullis/Desktop/F1DataProject/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/jeremybullis/Desktop/F1DataProject/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/jeremybullis/Desktop/F1DataProject/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/jeremybullis/Desktop/F1DataProject/app/templates/base.html", line 29, in top-level template code
    <option value="{{ r }}" {% if requests.args.get('race') == r|string %}selected{% endif %}>{{ r }}</option>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremybullis/Desktop/F1DataProject/venv/lib/python3.11/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'requests' is undefined
2025-10-06 13:29:04,366 INFO: Microblog startup [in /Users/jeremybullis/Desktop/F1DataProject/app/__init__.py:32]
2025-10-06 13:30:50,529 INFO: Microblog startup [in /Users/jeremybullis/Desktop/F1DataProject/app/__init__.py:32]
2025-10-06 16:22:13,786 INFO: Microblog startup [in /Users/jeremybullis/Desktop/F1DataProject/app/__init__.py:32]
2025-10-06 16:23:14,386 INFO: Microblog startup [in /Users/jeremybullis/Desktop/F1DataProject/app/__init__.py:32]
2025-10-06 16:27:09,863 INFO: Microblog startup [in /Users/jeremybullis/Desktop/F1DataProject/app/__init__.py:32]
2025-10-06 16:28:03,060 INFO: Microblog startup [in /Users/jeremybullis/Desktop/F1DataProject/app/__init__.py:32]
