2025-10-04 11:54:18,715 ERROR: Exception on /login [GET] [in C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\routes.py", line 43, in login
    return render_template('login.html', register_form=RegistrationForm(), login_form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\base.html", line 42, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\login.html", line 66, in block 'content'
    {{ form.hidden_tag() }}
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-10-04 11:55:06,682 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-04 11:56:24,326 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-04 11:57:29,359 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-04 12:01:50,806 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-04 12:02:15,456 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-04 12:25:45,833 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:08:33,500 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:20:18,014 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:20:40,410 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:20:56,680 ERROR: Exception on /register [POST] [in C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\wtforms\validators.py", line 401, in __call__
    import email_validator
ModuleNotFoundError: No module named 'email_validator'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\routes.py", line 55, in register
    if form.validate_on_submit():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask_wtf\form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\wtforms\form.py", line 330, in validate
    return super().validate(extra)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\wtforms\form.py", line 147, in validate
    if not field.validate(self, extra):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\wtforms\fields\core.py", line 234, in validate
    stop_validation = self._run_validation_chain(form, chain)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\wtforms\fields\core.py", line 254, in _run_validation_chain
    validator(form, self)
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\wtforms\validators.py", line 403, in __call__
    raise Exception(
Exception: Install 'email_validator' for email validation support.
2025-10-05 14:21:44,602 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:23:52,310 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:25:32,382 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:26:33,859 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:27:59,950 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:30:18,534 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:30:29,387 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:31:02,880 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:37:48,165 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:39:08,098 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:41:12,304 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:43:06,490 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:43:27,267 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:43:54,732 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:44:38,200 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:45:01,501 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:45:33,279 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:46:10,383 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:47:54,737 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:49:53,559 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-05 14:50:10,682 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-06 15:22:49,015 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
